version: "3.8"

services:
    app:
        build:
            context: ./docker # ビルドコンテキストはプロジェクトのルートディレクトリ
            dockerfile: php/Dockerfile # Dockerfileへの相対パスはcontextディレクトリ内の相対パス
        container_name: php_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        environment:
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=user
            - DB_PASSWORD=iwasaki
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: iwasaki
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

volumes:
    db_data:

networks:
    laravel:
